### ISSUE TITLE
Create empty directory 'templates' on first start

### ISSUE THREAD

**Issue by GiantCrocodile** [emmett-framework/emmett#144]
Like languages, logs and static there should be an empty directory called 'templates' being created on first weppy launch.

**Comment by mijdavis2** [comment]
The only reason I'd argue against that is if you were using a weppy instance strictly as an api for backend processes. Though IMO and in your defense it is always helpful for even a backend api behind a vpn/vpc to have an "about" or "doc" page for developers using it. Maybe weppy is overkill for a simple backend api, but it's just so darn convenient.

**Comment by gi0baro** [comment]
@GiantCrocodile the reason *templates* folder is not created on application launch are mainly:

- because you can customize the folder name, so it would be *pointless* to create the directory if you're using another directory for the templates
- because as @mijdavis2 said, if you're using weppy to make just APIs, you don't need templates at all

I think this behaviour wouldn't be changed. Probably, the changes on folder creation will be to avoid creating them at all, but this will be inspected carefully considering the next versions and the development process.

**Comment by GiantCrocodile** [comment]
Okay but why do we create other folders then? @mijdavis2 argument is applying too if you have no static files or no need for different languages.

I've created this issue because when I started a new project after some time I forgot where to place the templates. So I looked it up in the docs and I found with bad luck a place where the folders default name for templates was wrong (by a small typo: template, not templates). Then I struggled because it won't render still. This could have be prevented with an already existing folder like the other folders.
