### ISSUE TITLE
rowattr and services

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#199]
Hi @gi0baro 
In versions prior to 1.0 (tested with 0.8.2) the rowattr were injected into the services.
Why was this feature removed?

Jose

**Comment by gi0baro** [comment]
@josejachuf you mean the serialization? This is due to some performance refactoring happened for the 1.0. They are actually serialized if you access those attributes before returning the object. The idea is that if you need advanced serialization you should use weppy-REST.

This may change in 2.0, it depends on the ORM refactoring.

**Comment by josejachuf** [comment]
@gi0baro In this case for example:

```
@app.route("/ws2")
@service.json
def ws2():
    rows = Todo.all().select()
    return rows

```

**Comment by gi0baro** [comment]
@josejachuf yes, see what I wrote above.

**Comment by josejachuf** [comment]
What do you think of doing that you can configure the behavior?

**Comment by gi0baro** [comment]
I'm afraid would be very hard with the current implementation. Will think about a solution for this.
