### ISSUE TITLE
Not found on pypi

### ISSUE THREAD

**Issue by waghanza** [emmett-framework/emmett#250]
Hi,

According to `README`, I can install `emett` using `pip`

However, `pip install emmett` display me an error
~~~python
Collecting emmett
  ERROR: Could not find a version that satisfies the requirement emmett (from versions: none)
ERROR: No matching distribution found for emmetthttps://pypi.org/project/emmett/
~~~

I can see that https://pypi.org/project/emmett/ has no package. Is there any reason this is not pushed on pypi ?

Regards,

**Comment by gi0baro** [comment]
Hi @waghanza,
I’ve just updated the Readme removing the pip installation info, since at the moment Emmett is in alpha stage and not public alpha had been published yet.
You can still install it directly from source if you like to run experiments with it.

More info regarding next release are available here https://github.com/emmett-framework/emmett/issues/194#issuecomment-557630152, and the actual released version of the framework (1.x series) is available on pypi under the name of `weppy`, see also the 1.x branch here or the [weppy website](weppy.org).

**Comment by waghanza** [comment]
ok, so I will wait for **2.0** to achieve https://github.com/the-benchmarker/web-frameworks/issues/1931
