### ISSUE TITLE
Clearing sessions from a Post request

### ISSUE THREAD

**Issue by ianshk** [emmett-framework/emmett#290]
I wondered how it is possible to clear (pop) the sessions from a Post requests.

I have a situation where a post request comes in from a webhook and I need to clear a token which is stored in the session. I don't seem to have access to the session from a Post request though.

I tried just expiring the emmett cookie using Expires = 0 with simplecookie but it seems the cookie can't be cleared in anyway.

**Comment by gi0baro** [comment]
I think the issue here is not the POST request, but the fact an incoming webhook doesn't not contain any cookie, as its not made by a user.

Probably the best way is to store the token somewhere else (database, redis, etc.) and load it with a `Pipe` on the standard user request flow. Then you can just drop it with the webhook from the storage.

**Comment by ianshk** [comment]
I will try that, thanks gi0baro
