### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#294]
Hi, I was trying to use mongodb, but an error occurs when applying a migration (migrations up) with the following error:

**[Blank database, just created]**

> venv38/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
>     raise OperationFailure(msg % errmsg, code, response,
> pymongo.errors.OperationFailure: Failed to parse: { find: "emmett_schema", filter: { _id: { $gt: ObjectId('000000000000000000000000') } }, snapshot: false, projection: { id: "_id", version: "version" }, lsid: { id: UUID("2eb7a359-6ca0-4503-b505-1bf47bff61ff") }, $db: "mydb", $readPreference: { mode: "primaryPreferred" } }. Unrecognized field 'snapshot'., full error: {'ok': 0.0, 'errmsg': 'Failed to parse: { find: "emmett_schema", filter: { _id: { $gt: ObjectId(\'000000000000000000000000\') } }, snapshot: false, projection: { id: "_id", version: "version" }, lsid: { id: UUID("2eb7a359-6ca0-4503-b505-1bf47bff61ff") }, $db: "mydb", $readPreference: { mode: "primaryPreferred" } }. Unrecognized field \'snapshot\'.', 'code': 9, 'codeName': 'FailedToParse'}

Jose

**Comment by gi0baro** [comment]
@josejachuf probably I should improve the migrations docs, because **MongoDB is not supported** by Emmett's migration system (and there are no plans to add this kind of support in future).

FYI: there's actually [this personal repository](https://github.com/gi0baro/emmett-mongo) with a _Work In Progress_ wrapper around pymongo, but it's not using any ORM. In case you wondering why it is actually used by [this REST implementation](https://github.com/gi0baro/emmett-mongorest) which is a _Work In Progress_ as well. No idea if it sounds interesting for your specific needs.
