### ISSUE TITLE
Bug doing put in model whit unique field (version 2.4.5)

### ISSUE THREAD

**Issue by josejachuf** [emmett-framework/emmett#428]
I have a model with a unique field, if I make a put (using Emmett-REST) I get an error in which you do not be valid and forces me to change name value
```

class MyModel(Model):
    tablename = "my_model"

    name = Field.string(length=100, unique=True)
    start = Field.date()
    end = Field.date()
    
    validation = {
        'name': {'presence': True},
        'start': {'format': '%d/%m/%Y'},
        'end': {'format': '%d/%m/%Y'},       
    }

```

This fails with these versions:

> emmett 2.4.5
> emmett-rest 1.4

and works fine whit:

> emmett 2.3.1
> emmett-rest 1.2.0

**Comment by josejachuf** [comment]
Error also with

> emmett 2.4.5
> emmett 2.3.1

**Comment by gi0baro** [comment]
@josejachuf unfortunately, the `unique` validator is still based on the pretty-old pyDAL implementation. I already planned some changes for 2.5 in regard of models validations, but with 2.4 there's no easy way support this.

In order to solve your issue in the meantime you have two options:

i) rely on index constraint only, dropping the `unique` parameter from you field and implementing the validation logic manually on the "controller" side
ii) hack the validation in your REST endpoint (I would say in a `before_update` callback) doing what [forms](https://github.com/emmett-framework/emmett/blob/master/emmett/forms.py#L397) do, eg:

```python
@your_rest_module.before_update
def _fix_unique_validator(row, params):
    current._dbvalidation_record_id_ = row.id
```

I gonna keep this open until I write down a proper feature change for 2.5

**Comment by gi0baro** [comment]
I'm closing this in favour of #433
